# Generated by Django 5.0.2 on 2024-03-07 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cpf_cnpj", models.CharField(max_length=18)),
                ("endereco", models.CharField(blank=True, max_length=200, null=True)),
                ("telefone", models.CharField(max_length=200)),
                ("obs", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="produto",
            name="criado",
        ),
        migrations.AddField(
            model_name="produto",
            name="data_validade",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="estoque",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="fabricante",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
