# Generated by Django 5.0.2 on 2024-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_fornecedor_remove_produto_criado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="data_validade",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="fabricante",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
